com.fasterxml.jackson.*:* = 2.21.1
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
com.google.guava:guava = 33.4.8-jre
com.palantir.conjure:* = 4.0.0
com.palantir.baseline:* = 6.32.0
com.palantir.remoting-*:* = 1.8.0
com.palantir.ri:resource-identifier = 2.14.0
com.palantir.safe-logging:* = 3.13.0
com.palantir.syntactic-paths:syntactic-paths = 0.13.0
com.palantir.tokens:* = 4.2.0
com.squareup.okhttp3:* = 4.12.0
commons-cli:commons-cli = 1.9.0
io.dropwizard.metrics:metrics-core = 4.2.38
junit:junit = 4.13.2
org.apache.commons:commons-lang3 = 3.20.0
org.assertj:* = 3.27.7
org.hamcrest:hamcrest-core = 3.0
org.immutables:* = 2.10.1
org.javassist:javassist = 3.22.0-GA
org.slf4j:* = 2.0.17
